name: Build check for develop

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - 'CONTRIBUTORS.md'

  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - 'CONTRIBUTORS.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and start database
        run: |
          cd scripts/database-launch-starter
          chmod +x database-launch-starter.bash
          ./database-launch-starter.bash

      - name: Wait for database to start
        run: |
          while ! nc -z localhost 5432; do sleep 1; done

      - name: Build project
        run: |
          mvn clean install -T 1C

      - name: Run unit tests
        run: |
          mvn test

      - name: Check test results
        run: |
          mvn surefire-report:report-only
          cat target/site/surefire-report.html